# Generated by Django 4.1.7 on 2023-03-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('contact', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('milestones', models.TextField()),
                ('financials', models.TextField()),
                ('contact', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('smart_contract', models.CharField(blank=True, max_length=100)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igniteapp.startup')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igniteapp.startup')),
            ],
        ),
    ]
