# Generated by Django 4.1.7 on 2023-03-05 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igniteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('smart_contract', models.CharField(blank=True, max_length=100)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='igniteapp.customuser')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igniteapp.startup')),
            ],
        ),
    ]
