# Generated by Django 4.1.7 on 2023-03-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igniteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='Members',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
